In [1]:
import datetime
import os
import matplotlib
import matplotlib.dates as mdates
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from notebook_shared import utils

from statsmodels.tsa.seasonal import seasonal_decompose
from pandas import Series

import seaborn as sns
sns.set()
matplotlib.style.use('seaborn-colorblind')

INPUT_FILE = "dataset"
FSIZE = "tiny"

df = pd.read_parquet(utils.get_dataset_path(INPUT_FILE, FSIZE))

In [6]:
df.columns

Index(['driver_invocation', 'workload_invocation', 'provider', 'region',
       'dirty_measurement', 'folder_uuid', '1_run_id', '2_thread_id',
       'SAAFMemoryDeltaError', 'SAAFMemoryError', 'contextSwitches',
       'contextSwitchesDelta', 'cpuIdle', 'cpuIdleDelta', 'cpuIowait',
       'cpuIowaitDelta', 'cpuIrqDelta', 'cpuKrn', 'cpuKrnDelta', 'cpuModel',
       'cpuNice', 'cpuSoftIrq', 'cpuSoftIrqDelta', 'cpuType', 'cpuUsr',
       'cpuUsrDelta', 'endTime', 'frameworkRuntime', 'frameworkRuntimeDeltas',
       'freeMemory', 'functionName', 'latency', 'linuxVersion', 'newcontainer',
       'roundTripTime', 'runtime', 'runtimeOverlap', 'startTime',
       'totalMemory', 'userRuntime', 'uuid', 'vmcpusteal', 'vmcpustealDelta',
       'vmuptime', 'containerID', 'functionMemory', 'pageFaults',
       'pageFaultsDelta', 'vmID', 'dow_utc', 'tod_utc', 'timezone',
       'measure group', 'local_dow', 'local_tod'],
      dtype='object')

In [9]:
df_daily = df.groupby(['driver_invocation', 'provider', 'region', 'local_dow'])[['runtime']].mean().reset_index()

In [10]:
df_daily

              driver_invocation provider          region  local_dow    runtime
0       2021-08-01 13:30:03.035      AWS  ap-northeast-1     Friday       <NA>
1       2021-08-01 13:30:03.035      AWS  ap-northeast-1     Monday       <NA>
2       2021-08-01 13:30:03.035      AWS  ap-northeast-1   Saturday       <NA>
3       2021-08-01 13:30:03.035      AWS  ap-northeast-1     Sunday  65.333333
4       2021-08-01 13:30:03.035      AWS  ap-northeast-1   Thursday       <NA>
...                         ...      ...             ...        ...        ...
1766704 2021-09-30 23:30:03.438      GCP         westus2   Saturday       <NA>
1766705 2021-09-30 23:30:03.438      GCP         westus2     Sunday       <NA>
1766706 2021-09-30 23:30:03.438      GCP         westus2   Thursday       <NA>
1766707 2021-09-30 23:30:03.438      GCP         westus2    Tuesday       <NA>
1766708 2021-09-30 23:30:03.438      GCP         westus2  Wednesday       <NA>

[1766709 rows x 5 columns]

In [16]:
df_daily[(df_daily['provider'] == 'AWS') & (df_daily['region'] == 'ap-northeast-1')].groupby(['local_dow']).mean()

             runtime
local_dow
Friday     69.798507
Monday     69.496503
Saturday   68.924913
Sunday      69.06304
Thursday   69.426914
Tuesday     69.80517
Wednesday  69.559551